name = "magpic"
main = "./.cloudflare/worker.js"
compatibility_date = "2025-01-07"

# Static Assets設定
assets = { directory = "./.cloudflare/public", binding = "ASSETS" }

# KVネームスペース（OAuth2トークン保存用）
[[kv_namespaces]]
binding = "TOKENS"
id = "464adaa8094644bd94c11eed7c1b2326"

# 環境変数（Google OAuth2用）
# 実際の値はCloudflare Workersの環境変数として設定してください
[vars]
# GOOGLE_CLIENT_ID = "set via wrangler secret put"
# GOOGLE_CLIENT_SECRET = "set via wrangler secret put" 
# SESSION_SECRET = "set via wrangler secret put"

# プレビュー環境設定（PR用）
[env.preview]
name = "magpic-preview"

# ルーティング設定
# route = { pattern = "example.com/*", zone_name = "example.com" }

# 開発環境設定
[env.development]
name = "magpic-dev"
# vars = { MY_VARIABLE = "development value" }

# 本番環境設定
[env.production]
name = "magpic"
# vars = { MY_VARIABLE = "production value" }